---

version: '3.8'
services:
  web:
    build: ./nginx
    ports: 
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./work:/var/www
      - ./work/app:/var/www/app
      - ./work/public:/var/www/public
    restart:  always
    depends_on:
      - php
  db:
    build: ./mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: myapp
      MYSQL_USER: myappuser
      MYSQL_PASSWORD: myapppass
    volumes:
    - ./mysql/db-data:/var/lib/mysql
  php:
    build: .
    depends_on:
    - db
    volumes:
    - ./work:/var/www

volumes:
  db-data: